# whitelist
branches:
  only:
    - master
sudo: required
services: 
  - docker
language: ruby
rvm:
  - 2.2.3
# before_install:
#before_script:
script:
  - bundle exec rspec spec/
after_success:
  # - ls -alth
  - docker build -t matchbox/nci-match-patient-api .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag -f matchbox/nci-match-patient-api matchbox/nci-match-patient-api:latest
  - docker images
  - docker push matchbox/nci-match-patient-api:latest
  #Deploy to AWS IntTest
  - docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy --cluster PedMatch-IntTest --service-name uMatch-nci-match-patient-api-INTTEST -i matchbox/nci-match-patient-api:latest
#Trigger Travis bdd tests
  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json" -H "Travis-API-Version:3" -H "Authorization:token $TRAVIS_TOKEN" -d "{\"request\":{\"message\":\"Triggered by nci-match-patient-api $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=nci-match-patient-api;CUC_TAG=@patients\"]}}}}" https://api.travis-ci.org/repo/CBIIT%2Fnci-uMatch-bddtests/requests
#after_script:
notifications:
  slack:
    secure: iWEoDxHvZuFuTQHm0pZxHfyBr/QzV/yzzPWOTx8blvNNupSxxjVV1r5bv+8gQAV2evuH0H/ixQ/0OmwY1pwH7+BWoTujO49iUFW2XnYZlGkKgjQKmJzCO2zuZtGFnT6JKCrUJMEv5Hhk+CNNdi304H7BV/KqxoFyQxKah5os+ZtipybBHmzaVmspvbb9fJB4X6SpcXI/KylqguevSQBWj74oGMmEtwj87hKMc5aW4vpGTGnceNmpY7QFudDmKufvkFhV3fStA5hj3Ce7B6zPehhNEZejAJ6a7dmv29RCR/OeMkG/VQrgaw9+l+3iGU40AdaiVa3WsMIqBwwnhCSxUwNe91KlNeUJ2faIC/o39vvom177D0ABejVHnp4RlCViWbiysdT+w8dw2mQQdPGl+o4iGlBAcRA+vlFKXMGpbOGcz4IPMNO7qfF2wueL7/pEjExmoQgIeuRvZEd58AHhm+WlqejSYhyRJ+xDqoeG0wppb8xoHuQsapi/f26Lh+ulyItsV0EOLxavfruAiNwAlBBxphyWHNar26LZtb0AsJ2FkU+Ikj5h0jFOY9LVyZCN0shDUmunqBgEtTTMAGYAVvBUAiVeqPG3NCG5yXbZ1xZARiBZEWQbhnUxhzMysvmoJTo1NQIbxB+nONH6tsSuHoxaPllSJaC3KU9lJbe9fO4=
addons:
  code_climate:
    repo_token:
      secure: FKlJti2G15VBf3UDdo4G6ul00vEQXCpga5bjvtNOvPgEqe1z024fwLYV4N9APBsGAersieWUCrW2hvOdTsFVgAVs1tEfPkseC+UFLOZvzF/PlhLn3zymsPkr5resgZPMLZhE6zX2PzlicloEqz2OSPhrcL+GfwnBHoHp7pFk61uH7QzEjTBUkbUeYag0IIItvWFPeIMNM7jG4VANhdHpevmJufn4mZz60QVRR32amzQQgWo0Jxtlpryxll8LPKi9ioQN1hn6G7VCNwudR1QzV19Gp48kLwsoEkESiS/lgLecXcw6yKpi2rVN/rgfyn+mKJ+Zou8TKBs1Sffk5S+7ucCj4t6QHjJYcNyxU0gVj8Xo2bq23eUZn490hK5RwxnCd+c5MYU9k8NVfwiZIuhhD9a6E9GGgoxXvrpmWSIug37LpIeyzcVGH5lTtVKwFR0jx1RBbbvnmPC/BHSx+HbdMTlcYrhcYbY2CC1tmIYoy0/O3z+sv+pKRUWTeG2GR+FF4CqzXPyDtboIxIpttqKU0c3jkO007NMD/8gnMqj+oGfGmePpMKooS6iahEtQdE7fvQV8un2/Ka0BzXNQgoCeIsPuLrXai3AtGIYRsJgSxLvJuJ/ilNkB5IE5eLTuwbonabmHdjghE/Y1zzgaIYIn8zkrkK8zUVlkRSXP+FkEm3k=
