language: ruby
rvm:
- 2.2.3
notifications:
  slack:
    secure: iWEoDxHvZuFuTQHm0pZxHfyBr/QzV/yzzPWOTx8blvNNupSxxjVV1r5bv+8gQAV2evuH0H/ixQ/0OmwY1pwH7+BWoTujO49iUFW2XnYZlGkKgjQKmJzCO2zuZtGFnT6JKCrUJMEv5Hhk+CNNdi304H7BV/KqxoFyQxKah5os+ZtipybBHmzaVmspvbb9fJB4X6SpcXI/KylqguevSQBWj74oGMmEtwj87hKMc5aW4vpGTGnceNmpY7QFudDmKufvkFhV3fStA5hj3Ce7B6zPehhNEZejAJ6a7dmv29RCR/OeMkG/VQrgaw9+l+3iGU40AdaiVa3WsMIqBwwnhCSxUwNe91KlNeUJ2faIC/o39vvom177D0ABejVHnp4RlCViWbiysdT+w8dw2mQQdPGl+o4iGlBAcRA+vlFKXMGpbOGcz4IPMNO7qfF2wueL7/pEjExmoQgIeuRvZEd58AHhm+WlqejSYhyRJ+xDqoeG0wppb8xoHuQsapi/f26Lh+ulyItsV0EOLxavfruAiNwAlBBxphyWHNar26LZtb0AsJ2FkU+Ikj5h0jFOY9LVyZCN0shDUmunqBgEtTTMAGYAVvBUAiVeqPG3NCG5yXbZ1xZARiBZEWQbhnUxhzMysvmoJTo1NQIbxB+nONH6tsSuHoxaPllSJaC3KU9lJbe9fO4=
