# whitelist
branches:
  only:
    - master
sudo: required
services:
  - docker
language: ruby
rvm:
  - 2.3.4
before_install:
  #Set up Docker exports
  - export AUTHOR=`git --no-pager show -s --format='%an <%ae>'`
  - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
  - export DOCKER_IMAGE="fnlcr/nci-match-patient-api"
  - echo "TravisBuild=$TRAVIS_BUILD_NUMBER" > build_number.html &&
        echo "Commit=$TRAVIS_COMMIT" >> build_number.html       &&
        echo "TravisBuildID=$TRAVIS_BUILD_ID" >> build_number.html    &&
        echo "Author=$AUTHOR" >> build_number.html              &&
        echo "BuildTime=$DATE" >> build_number.html             &&
        echo "Docker=$DOCKER_IMAGE:$DATE" >> build_number.html
  - cat ./build_number.html
script:
  - RAILS_ENV=test bundle exec rspec spec/
  #Build Docker image
  - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # - docker run -it --rm -e "RAILS_ENV=test" $DOCKER_IMAGE:$DATE
  #     bundle exec rspec spec/
after_success:
  - docker images
  - docker push $DOCKER_IMAGE # Pushes both date and latest
  #Deploy to AWS IntTest
  - docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy
    --cluster PedMatch-IntTest-Backend --service-name PedMatch-nci-match-patient-api-INTTEST
    -i $DOCKER_IMAGE:$DATE
  #Trigger Travis bdd tests
  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json"
    -H "Travis-API-Version:3" -H "Authorization:token $TRAVIS_TOKEN"
    -d "{\"request\":{\"message\":\"Triggered by nci-match-patient-api $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=nci-match-patient-api;TRIGGER_VER=$DATE;TRIGGER_COMMIT=$TRAVIS_COMMIT;TRIGGER_DOCKER_IMAGE=$DOCKER_IMAGE;CUC_TAG=@patients;AUTHOR=$AUTHOR\"]}}}}"
    https://api.travis-ci.org/repo/CBIIT%2Fnci-uMatch-bddtests/requests
notifications:
  slack: clinicalbiomed:gRp5LqKElNOjUUMPLlq4qC1j
addons:
