common: &default
  ICCPTENs:
    start_date: "Jan 1 2017"
  ICCBAF47s:
    start_date: "Jan 1 2017"
  ICCBRG1s:
    start_date: "Jan 1 2017"

development:
  <<: *default
test:
  <<: *default
uat:
  <<: *default
production:
  <<: *default