common: &default
  ICCPTENs:
    start_date: "Jan 1 2017"
  ICCBAF47s:
    start_date: "Jan 1 2017"
  ICCBRG1s:
    start_date: "Jan 1 2017"

development:
  <<: *default
  ICCBRG1s:
    start_date: "Jan 1 2016"

test: &test
  <<: *default
  ICCPTENs:
    start_date: "Jan 1 2016"
  ICCBAF47s:
    start_date: "Jan 1 2016"
  ICCBRG1s:
    start_date: "Jan 1 2016"
  # ICCBRG1s_in_past:
  #   start_date: "Jan 1 2016"
  #   end_date: "Jan 1 2016"

test_local:
  <<: *default
  <<: *test

uat:
  <<: *default

production:
  <<: *default
