development:
  aws_dynamo_endpoint: "http://localhost:8000"
  aws_region: "us-east-1"

  queue_name: "sy_patient_development"

  # dynamodb setting
  read_capacity_units: "30"
  write_capacity_units: "30"

test:
  aws_dynamo_endpoint: "http://localhost:8000"
  aws_region: "us-east-1"

  queue_name: "patient_test"

  # dynamodb setting
  read_capacity_units: "5"
  write_capacity_units: "5"

uat:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"

  #Constructed queue name: "patient_processor"
  queue_name: "patient_uat"

  # dynamodb setting
  read_capacity_units: "5"
  write_capacity_units: "5"

production:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"

  #Constructed queue name: "patient_processor"
  queue_name: "patient"

  # dynamodb setting
  read_capacity_units: "5"
  write_capacity_units: "5"