common: &defaults
  aws_region: "us-east-1"
  s3_url: "https://s3.amazonaws.com"
  auth0_domain: "https://ncimatch.auth0.com"
  auth0_base64_encoded_secret: <%= ENV["AUTH0_BASE64_ENCODED_SECRET"].to_s %> # true/false string

  # do not put aws cluster config endpoint here, use single node (we dont have auto-discovery)
  memcached_node_endpoint: <%= ENV["MEMCACHED_NODE_ENDPOINT"] %>

development:
  <<: *defaults
  aws_dynamo_endpoint: "http://localhost:8000"
  slack_channel: "#match-bot-dev"

  queue_name: <%= ENV["PATIENT_QUEUE_NAME="] %>

  # dynamodb setting
  read_capacity_units: "30"
  write_capacity_units: "30"

  patient_state_api: "http://localhost:10241/api/v1/state_validator/"
  patient_processor: "http://localhost:3010"
  match_rule_api: "http://127.0.0.1:10250/api/v1/rules/"
  treatment_arm_api: "localhost:10235/api/v1/treatment_arms"

  s3_bucket: "pedmatch-dev"
  auth0_connection: "MATCH-Development"

test: &test
  <<: *defaults
  slack_channel: "#match-bot-int"
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  queue_name: 'patient_queue'

  # dynamodb setting
  read_capacity_units: "5"
  write_capacity_units: "5"

  patient_state_api: "https://pedmatch-int.nci.nih.gov/api/v1/state_validator/"
  patient_processor: "https://pedmatch-int.nci.nih.gov:3010"
  match_rule_api:    "https://pedmatch-int.nci.nih.gov/api/v1/rules/"
  treatment_arm_api: "https://pedmatch-int.nci.nih.gov/api/v1/treatment_arms"

  http_read_timeout: "120"

  s3_bucket: "pedmatch-int"
  auth0_connection: "MATCH-IntTest"

test_local:
  <<: *defaults
  <<: *test

uat:
  <<: *defaults
  slack_channel: "#match-bot-uat"
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  #Constructed queue name: "patient_processor"
  queue_name: 'patient_queue'

  # dynamodb setting
  read_capacity_units: "5"
  write_capacity_units: "5"

  patient_state_api: "https://pedmatch-uat.nci.nih.gov/api/v1/state_validator/"
  patient_processor: "https://pedmatch-uat.nci.nih.gov:3010"
  match_rule_api:    "https://pedmatch-uat.nci.nih.gov/api/v1/rules/"
  treatment_arm_api: "https://pedmatch-uat.nci.nih.gov/api/v1/treatment_arms/"

  s3_bucket: "pedmatch-uat"
  auth0_connection: "MATCH-UAT"

production:
  <<: *defaults
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  slack_channel: "#match-bot-prod"
  #Constructed queue name: "patient_processor"
  queue_name: 'patient_queue'

  # dynamodb setting
  read_capacity_units: "5"
  write_capacity_units: "5"

  patient_state_api: "https://pedmatch.nci.nih.gov/api/v1/state_validator/"
  patient_processor: "https://pedmatch.nci.nih.gov:3010"
  match_rule_api:    "https://pedmatch.nci.nih.gov/api/v1/rules/"
  treatment_arm_api: "https://pedmatch.nci.nih.gov/api/v1/treatment_arms/"

  s3_bucket: "pedmatch"
  auth0_connection: "MATCH-Production"
