development:
  aws_dynamo_endpoint: "http://localhost:8000"
  aws_region: "us-east-1"

  queue_name: ""

  # dynamodb setting
  read_capacity_units: "30"
  write_capacity_units: "30"

  patient_state_api: "http://localhost:10241/"
  patient_processor: "http://localhost:10242"

  s3_url: "https://s3.amazonaws.com"

test:

  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region_dynamo: "us-east-1"
  aws_region: "us-east-1"

  queue_name: "patient_test"

  # dynamodb setting
  read_capacity_units: "5"
  write_capacity_units: "5"

  shoryuken_delay: "30"
  shoryuken_concurrency: "30"

  patient_state_api: "http://pedmatch.org:10241/"
  patient_processor: "http://pedmatch.org:3010"

  http_read_timeout: "120"
  http_use_ssl: "false"

  s3_url: "https://s3.amazonaws.com"

uat:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"

  #Constructed queue name: "patient_processor"
  queue_name: "patient_uat"

  # dynamodb setting
  read_capacity_units: "5"
  write_capacity_units: "5"

  patient_state_api: "http://pedmatch.org:10241/"
  patient_processor: "http://localhost:10242"

  s3_url: "https://s3.amazonaws.com"

production:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"

  #Constructed queue name: "patient_processor"
  queue_name: "patient"

  # dynamodb setting
  read_capacity_units: "5"
  write_capacity_units: "5"

  patient_state_api: "http://pedmatch.org:10241/"
  patient_processor: "http://localhost:10242"

  s3_url: "https://s3.amazonaws.com"
