development:
  aws_dynamo_endpoint: "http://localhost:8000"
  aws_region: "us-east-1"

  # queue_prefix could be empty. Environment is the suffix, added by default
  # Constructed queue name: "<prefix>_patient_development" - with valid prefix
  #                        "patient_development"            - with empty prefix
  queue_name: "patient"
  queue_prefix: "sy"
#  queue_suffix: "_dev_{:ENV:USER}"

  # table_prefix could be empty. Environment is the suffix, added by default
  # Constructed table name: "<prefix>_patient_events_development" - with valid prefix
  #                        "patient_event_development"            - with empty prefix
  table_prefix: "ys"
  read_capacity_units: "30"
  write_capacity_units: "30"

test_local:
  aws_dynamo_endpoint: "http://localhost:8000"
  aws_region: "us-east-1"

  # queue_prefix could be empty. Environment is the suffix, added by default
  # Constructed queue name: "<prefix>_patient_development" - with valid prefix
  #                        "patient_development"            - with empty prefix
  queue_name: "patient"
  queue_prefix: "tl"
#  queue_suffix: "_dev_{:ENV:USER}"

  # table_prefix could be empty. Environment is the suffix, added by default
  # Constructed table name: "<prefix>_patient_events_development" - with valid prefix
  #                        "patient_event_development"            - with empty prefix
  table_prefix: "tl"
  read_capacity_units: "5"
  write_capacity_units: "5"

test:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"

  #Constructed queue name: "patient_processor"
  queue_name: "patient"
  queue_prefix: "ts"
#  queue_suffix: ""

  #Constructed table name: "patient_events"
  table_prefix: "ts"
  read_capacity_units: "5"
  write_capacity_units: "5"

uat:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"

  #Constructed queue name: "patient_processor"
  queue_prefix: "p_"
  queue_suffix: ""

  #Constructed table name: "patient_events"
  table_prefix: "p_"
  read_capacity_units: "5"
  write_capacity_units: "5"

production:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"

  #Constructed queue name: "patient_processor"
  queue_prefix: "p_"
  queue_suffix: ""

  #Constructed table name: "patient_events"
  table_prefix: "p_"
  read_capacity_units: "50"
  write_capacity_units: "50"