# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edc76d98e9f32c48cf6da34aa3bf6bd4f15cb9d4c00494e444090b616bec270e5ca771c43a00921dd51cc084c8e4ad4fa530598bc5ee91b17107b7c34c5e57fd
  aws_access_key_id: "AKIAIXFXLSHZ63A6LALA"
  aws_secret_access_key: "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"
test:
  secret_key_base: 149ae06fbfca343a3d0fcbb78dc9b6f701e39645b6df6ef2c7b032f3830c831e80316e421fa3a7b8bfe7c3e8c82d087be915dfd5969c49346c6b0a8ae05dd26f
  aws_access_key_id: <%= ENV["SECRET_KEY_BASE"] %>
  aws_secret_access_key: <%= ENV["SECRET_KEY_BASE"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
