# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
common: &defaults
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_management_id: <%= ENV["AUTH0_MANAGEMENT_ID"] %>
  auth0_management_secret: <%= ENV["AUTH0_MANAGEMENT_SECRET"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  slack_api_token: <%= ENV["SLACK_TOKEN"] %>

development:
  <<: *defaults
  secret_key_base: 81ae83576ab4a7abd1df10d25ef16bb03cee610780d7d280db8df1ef870a8c65d4889b1f0d2500d4ee3e784ed202455bb130be946d8de56966939ee721a19f91

test_local:
  <<: *defaults
  secret_key_base: b64e365a68f7946dc0f38a363f8b94acb014d92ac3422c87d2a5e1f577a46caa7a20d566af7dde5d4aa766882abc6a8531e6b63dcff57ceb1d6aabe18caf0ebe

test:
  <<: *defaults
  secret_key_base: b64e365a68f7946dc0f38a363f8b94acb014d92ac3422c87d2a5e1f577a46caa7a20d566af7dde5d4aa766882abc6a8531e6b63dcff57ceb1d6aabe18caf0ebe

inttest:
  <<: *defaults
  secret_key_base: b64e365a68f7946dc0f38a363f8b94acb014d92ac3422c87d2a5e1f577a46caa7a20d566af7dde5d4aa766882abc6a8531e6b63dcff57ceb1d6aabe18caf0ebe

uat:
  <<: *defaults
  secret_key_base: b64e365a68f7946dc0f38a363f8b94acb014d92ac3422c87d2a5e1f577a46caa7a20d566af7dde5d4aa766882abc6a8531e6b63dcff57ceb1d6aabe18caf0ebe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
  secret_key_base: b64e365a68f7946dc0f38a363f8b94acb014d92ac3422c87d2a5e1f577a46caa7a20d566af7dde5d4aa766882abc6a8531e6b63dcff57ceb1d6aabe18caf0ebe
